name: Multi-Environment CI/CD

on: [push]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Automated Tests
        run: |
          echo "Running Unit and Integration Tests"
          sleep 3  # Simulating test execution
          echo "Tests Passed"



  staging:
    runs-on: ubuntu-latest
    needs: onebox
    steps:
      - name: Deploy to Staging (Beta/Gamma)
        run: |
          echo "Deploying to Staging"
          sleep 3
          echo "Staging Deployment Successful"
